<x-app-layout>
    <x-slot name="header">
        <h1 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Terms and conditions') }}
        </h1>
    </x-slot>

    <div class="pt-4 pb-8 bg-gray-100 dark:bg-gray-800">
        <div class="flex flex-col items-center pt-6 sm:pt-0">
            <div
                class="w-full sm:max-w-5xl mt-6 p-6 bg-white dark:bg-gray-900 shadow-md overflow-hidden sm:rounded-lg prose">
                <h2 class="text-xl text-black dark:text-white">{{ __("General information") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("This website is operated by danidoble. Throughout the site, the terms \"we\", \"us\" and \"our\" refer to danidoble. danidoble offers this website, including all the information, tools and services available to you on this site, the user is conditioned to the acceptance of all the terms, conditions, policies and notifications established here.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("By visiting our site and / or purchasing something from us, you participate in our \"Service\" and accept the following terms and conditions (\"Terms of Service\", \"Terms\"), including all additional terms and conditions and policies to which referenced herein and / or available via hyperlinks. These Terms of Service apply to all users of the site, including without limitation users who are browsers, providers, clients, merchants, and / or content contributors.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("Please read these Terms of Service carefully before accessing or using our website. By accessing or using any part of the site, you are accepting the Terms of Service. If you do not agree to all the terms and conditions of this agreement, then you should not access the website or use any of the services. If the Terms of Service are considered an offer, acceptance is expressly limited to these Terms of Service.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("Any new features or tools added to the current store will also be subject to the Terms of Service. You can review the updated version of the Terms of Service at any time on this page. We reserve the right to update, change or replace any part of the Terms of Service by posting updates and / or changes to our website. It is your responsibility to check this page periodically for changes. Your continued use of or access to the website after the posting of any changes constitutes acceptance of those changes.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("Section 1 - online store terms") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("By using this site, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and that you have given us your consent to allow any of your dependents minors use this site.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("You may not use our products for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws).") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("You must not transmit worms, viruses or any code of a destructive nature.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("The breach or violation of any of these Terms will result in the immediate cessation of your Services.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("Section 2 - general conditions") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("We reserve the right to refuse the provision of service to anyone, for any reason and at any time.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("You understand that your content (not including your credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to adjust or adapt to technical networking or device connection requirements. Credit card information is always encrypted during transfer over networks.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("You agree not to reproduce, duplicate, copy, sell, resell or exploit any part of the Service, usp of the Service, or access to the Service or any contact on the website through which the service is provided, without the express permission of written from us.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("The titles used in this agreement are included for convenience only and do not limit or affect these Terms.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("Section 3 - accuracy, completeness and timeliness of information") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("We are not responsible if the information available on this site is not accurate, complete or current. The material on this site is provided for general information only and should not be relied upon or used as the sole basis for making decisions without first consulting more accurate, complete or timely information. Any reliance on the material on this site is at your own risk.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("This site may contain certain historical information. Historical information is not necessarily current and is provided for your reference only. We reserve the right to modify the contents of this site at any time, but we have no obligation to update any information on our site. You agree that it is your responsibility to monitor changes to our site.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400"></div>

                <h2 class="text-xl text-black dark:text-white">{{ __("Section 5 - Products or services (if applicable)") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("Certain products or services may be available exclusively online through the website. These products or services may have limited quantities and are subject to return or exchange according to our return policy only.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("We have made every effort to display the colors and images of our products, in the store, with the highest possible color accuracy. We cannot guarantee that your computer monitor will display colors exactly.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("We reserve the right, but are not obligated, to limit sales of our products or services to any person, geographic region, or jurisdiction. We can exercise this right on a case-by-case basis. We reserve the right to limit the quantities of the products or services that we offer. All product descriptions or product prices are subject to change at any time without notice, at our sole discretion. We reserve the right to discontinue any product at any time. Any product or service offer made on this site is void where prohibited.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("We do not guarantee that the quality of the products, services, information or other material purchased or obtained by you will meet your expectations, or that any errors in the Service will be corrected.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("SECTION 6 - ACCURACY OF BILLING AND ACCOUNT INFORMATION") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("We reserve the right to refuse any order you place with us. We may, at our discretion, limit or cancel the quantities purchased per person, per household or per order. These restrictions may include orders placed by or under the same customer account, the same credit card, and / or orders that use the same billing and / or shipping address.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("In the event that we make a change or cancel an order, we may attempt to notify you by contacting us via email and / or billing address / phone number provided at the time the order was placed. We reserve the right to limit or prohibit orders that, in our judgment, appear to be placed by dealers, resellers or distributors.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("You agree to provide current, complete and accurate information on the purchase and account used for all purchases made in our store. You agree to promptly update your account and other information, including your email address and credit card numbers and expiration dates, so that we can complete your transactions and contact you when necessary.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("For more details, please review our Returns Policy.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("SECTION 7 - OPTIONAL TOOLS") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("We may provide you with access to third-party tools that we do not monitor and over which we have no control or input.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("You acknowledge and agree that we provide access to these types of tools \"as is\" and \"as available\" without warranties, representations or conditions of any kind and without any endorsement. We will not have any responsibility derived from or related to your use of tools provided by third parties.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("Any use you make of the optional tools offered through the site is at your own risk and discretion and you must ensure that you are familiar with and approve of the terms under which these tools are provided by the third-party provider (s).") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("It is also possible that, in the future, we will offer you new services and / or features through the website (including the launch of new tools and resources). These new features and / or services will also be subject to these Terms of Service.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("SECTION 8 - THIRD PARTY LINKS") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("Certain content, products and services available via our Service may include material from third parties.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("Third party links on this site may direct you to third party websites that are not affiliated with us. We are not responsible for examining or evaluating content or accuracy and we do not warrant and will not have any liability or responsibility for any third party materials or websites, or for any third party materials, products or services.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("We are not responsible for any damage or damage related to the acquisition or use of goods, services, resources, content, or any other transaction made in connection with third party websites. Please carefully review the policies and practices of third parties and make sure you understand them before engaging in any transaction. Complaints, claims, concerns or questions regarding third party products should be directed to the third party.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("SECTION 9 - USER COMMENTS, FEEDBACK AND OTHER SUBMISSIONS") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("If, at our request, you send certain specific submissions (for example, participation in contests) or without a request from us, you send creative ideas, suggestions, proposals, plans, or other materials, either online, by email, by postal mail. , or otherwise (collectively, 'comments'), you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate or use by any means comments that you have submitted to us. We have and will not have any obligation (1) to keep any comments confidential; (2) to pay compensation for comments; or (3) to respond to comments.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("We can, but have no obligation, to monitor, edit or remove content that we consider to be illegitimate, offensive, threatening, libelous, defamatory, pornographic, obscene or objectionable or violates the intellectual property of any of the parties or the Terms of Service.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("You agree that your comments will not violate the rights of third parties, including copyright, trademark, privacy, personality or other personal or property rights. Likewise, you agree that your comments do not contain defamatory or illegal, abusive or obscene material, or contain computer viruses or other malware that could, in any way, affect the operation of the Service or any related website. You cannot use a false email address, use another identity that is not legitimate, or deceive third parties or us as to the origin of your comments. You are solely responsible for the comments you make and their accuracy. We are not responsible and do not assume any obligation with respect to the comments posted by you or any third party.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("SECTION 10 - PERSONAL INFORMATION") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("Your submission of personal information through the site is governed by our Privacy Policy. To view our Privacy Policy.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("SECTION 11 - ERRORS, INACCURACIES AND OMISSIONS") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("From time to time there may be information on our site or in the Service that contains typographical errors, inaccuracies or omissions that may be related to product descriptions, prices, promotions, offers, product shipping costs, transit time and the availability. We reserve the right to correct any errors, inaccuracies or omissions and to change or update information or cancel orders if any information in the Service or on any related website is inaccurate at any time without prior notice (including after you have submitted your order) .") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("We do not undertake any obligation to update, correct or clarify information in the Service or on any related website, including, without limitation, pricing information, except where required by law. No updated specification or update date applied in the Service or on any related website should be taken to indicate that all information in the Service or on any related website has been modified or updated.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("SECTION 12 - PROHIBITED USES") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("In addition to other prohibitions as established in the Terms of Service, the use of the site or its content is prohibited: (a) for any illegal purpose; (b) to ask others to carry out or participate in illegal acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe or violate our or third parties' intellectual property rights; (e) to harass, abuse, insult, damage, defame, slander, discredit, intimidate or discriminate on the basis of gender, sexual orientation, religion, ethnicity, race, age, national origin or disability; (f) to present false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that is or may be used in any way that may compromise the functionality or operation of the Service or any related website, other sites or the Internet; (h) to collect or track personal information of others; (i) to generate spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other sites or the Internet. We reserve the right to suspend use of the Service or any related website for violating any of the prohibited uses items.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("SECTION 13 - EXCLUSION OF WARRANTIES; LIMITATION OF LIABILITY") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("We do not guarantee or warrant that the use of our service will be uninterrupted, punctual, secure or error-free.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("We do not guarantee that the results that may be obtained from the use of the service will be accurate or reliable.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("You agree that from time to time we may remove service for indefinite periods of time or terminate service at any time without prior notice.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("You expressly agree that your use of, or the ability to use, the service is at your own risk. The service and all products and services provided through the service are (except as expressly stated by us) provided \"as is\" and \"as available\" for use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("Under no circumstances will our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any damage, loss, claim, or direct, indirect, incidental, punitive, special or consequential damages. of any kind, including, without limitation, loss of profits, loss of income, loss of savings, loss of data, replacement costs, or any similar damage, whether based on contract, tort (including negligence), strict liability or liability. otherwise, as a result of the use of any of the services or products acquired through the service, or for any other claim related in any way to the use of the service or any product, including but not limited to any errors or omissions in any content , or any loss or damage of any kind incurred as a result of using the service or any content (or product) published, transmitted, or made available through the service, even if it is advised of its possibility. Because some states or jurisdictions do not allow the exclusion or limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability will be limited to the maximum extent permitted by law.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("SECTION 14 - INDEMNIFICATION") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("You agree to indemnify, defend and hold harmless harmless and our parents, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensees, service providers, subcontractors, suppliers, interns and employees, from any claim or demand, including reasonable fees from lawyers, made by any third party due to or as a result of your breach of the Terms of Service or the documents that they incorporate as reference, or the violation of any law or the rights of or third party.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("SECTION 15 - SEVERABILITY") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("In the event that it is determined that any provision of these Terms of Service is illegal, null or unenforceable, said provision will be, however, effective to obtain the maximum extent allowed by applicable law, and the unenforceable part will be considered separate from these Terms of Service, such determination will not affect the validity of applicability of the other remaining provisions.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("SECTION 16 - TERMINATION") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("The obligations and responsibilities of the parties that have incurred prior to the termination date will survive the termination of this agreement for all purposes.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("These Terms of Service are effective unless and until terminated by either you or us. You can terminate these Terms of Service at any time by notifying us that you no longer wish to use our services, or when you stop using our site.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("If, in our judgment, you fail, or it is suspected that you have failed, to comply with any term or provision of these Terms of Service, we may also terminate this agreement at any time without prior notice, and you will remain responsible for all amounts owed until including the termination date; and / or consequently we may deny you access to our services (or any part of it).") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("SECTION 17 - ENTIRE AGREEMENT") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("Our failure to exercise or enforce any right or provision of these Terms of Service will not constitute a waiver of such right or provision.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("These Terms of Service and the policies or operating rules posted by us on this site or with respect to the service constitute the entire agreement and understanding between you and us and govern the use of the Service and supersede any prior or contemporaneous agreements, communications and proposals. , whether oral or written, between you and us (including, but not limited to, any prior version of the Terms of Service).") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("Any ambiguity in the interpretation of these Terms of Service will not be construed against the drafting group.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("SECTION 18 - LAW") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("These Terms of Service and any separate agreements in which we provide services to you will be governed by and construed in accordance with the laws of.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("SECTION 19 - CHANGES TO THE TERMS OF SERVICE") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("You can review the most current version of the Terms of Service at any time on this page.") }}</div>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("We reserve the right, at our sole discretion, to update, modify or replace any part of these Terms of Service by posting updates and changes on our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service after the posting of any changes to these Terms of Service constitutes acceptance of those changes.") }}</div>

                <h2 class="text-xl text-black dark:text-white">{{ __("SECTION 20 - CONTACT INFORMATION") }}</h2>
                <div class="text-md text-gray-700 dark:text-gray-400">{{ __("Questions about the Terms of Service should be sent to") }} {{ env('EMAIL_SUPPORT') }}</div>
            </div>
        </div>
    </div>
</x-app-layout>
